### PR TITLE
Fix fixt to work on rust latest rust

### LINKED ISSUE #329: Build fails with latest rust stable version (1.46)
The crate `fixt` fails to compile with latest version of stable rust (1.46), with several errors looking exactly like this one:

```
error[E0424]: expected value, found module `self`
   --> crates/fixt/src/serialized_bytes.rs:70:18
    |
70  |               .nth(self.0.index)
    |                    ^^^^ `self` value is a keyword only available in methods with a `self` parameter
    | 
   ::: crates/fixt/src/lib.rs:463:17
    |
463 | /                 fn next(&mut self) -> Option<Self::Item> {
464 | |                     let original_index = self.0.index;
465 | |                     let ret = $e;
466 | |                     if original_index == self.0.index {
...   |
469 | |                     Some(ret)
470 | |                 }
    | |_________________- this function has a `self` parameter, but a macro invocation can only access identifiers it receives from parameters
```

Build works fine in previous version (1.45.2).

### PR DESCRIPTION
**Pull request by freesig**
Fixes #329

### CODE REVIEW

**Review by Connoropolous — COMMENTED** [review]
Looks great! Could you change the note about rust version thats in docs/core_testing.md as part of this?

**Comment by Connoropolous** [comment]
Don't forget that you can update the pinned stable version of Rust in `Holonix` once you merge this, to 1.47.0 I think, that's what I've just tested this on.

**Review by maackle — APPROVED** [review]
Nice fix. I think this highlights the leaky abstraction in `fixt` of needing to manually track the index of a sequence rather than just having a proper iterator, but it's probably not worth addressing that now.

**Comment by chinoto** [comment]
Wow, much cleaner than my monstrosity! :+1:
