### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by guillemcordoba** [holochain/holochain#681]
Holochain fails to build with both cargo v1.49 and v1.48 with this error: 

```
error[E0597]: `__self` does not live long enough
   --> crates/holochain/src/conductor/handle.rs:278:9
    |
278 |           self.conductor
    |           -^^^
    |           |
    |  _________borrowed value does not live long enough
    | |
279 | |             .write()
280 | |             .await
    | |__________________- a temporary with access to the borrow is created here ...
...
283 |       }
    |       -
    |       |
    |       `__self` dropped here while still borrowed
    |       ... and the borrow might be used here, when that temporary is dropped and runs the `Drop` code for type `tokio::sync::RwLockWriteGuard`
    |
    = note: the temporary is part of an expression at the end of a block;
            consider forcing this temporary to be dropped sooner, before the block's local variables are dropped
help: for example, you could save the expression's value in a new local variable `x` and then make `x` be the expression at the end of the block
    |
278 |         let x = self.conductor
279 |             .write()
280 |             .await
281 |             .startup_app_interfaces_via_handle(self.clone())
282 |             .await; x
    |

```

cc @pospi

**Comment by pospi** [comment]
I'm actually getting this working with 1.49 but not 1.48; and IIRC you reported the reverse @guillemcordoba? So that's kinda weird. I thought cargo was pretty good at being deterministic but maybe we are hitting some staleness thing that `hn-flush` does not account for?

**Comment by artbrock** [comment]
We're releasing a new version of Holochain today (this weekend?). 

I'm assuming this issue is long in the past at this point. Can you confirm @guillemcordoba

**Comment by artbrock** [comment]
I'm pretty sure that now their we're on Rust 1.54 and Holochain release 0.0.104+ this is long in the past. I'm closing it.
