### ISSUE TITLE
Build fails with latest rust stable version (1.46)

### ISSUE THREAD

**Issue by guillemcordoba** [holochain/holochain#329]
The crate `fixt` fails to compile with latest version of stable rust (1.46), with several errors looking exactly like this one:

```
error[E0424]: expected value, found module `self`
   --> crates/fixt/src/serialized_bytes.rs:70:18
    |
70  |               .nth(self.0.index)
    |                    ^^^^ `self` value is a keyword only available in methods with a `self` parameter
    | 
   ::: crates/fixt/src/lib.rs:463:17
    |
463 | /                 fn next(&mut self) -> Option<Self::Item> {
464 | |                     let original_index = self.0.index;
465 | |                     let ret = $e;
466 | |                     if original_index == self.0.index {
...   |
469 | |                     Some(ret)
470 | |                 }
    | |_________________- this function has a `self` parameter, but a macro invocation can only access identifiers it receives from parameters
```

Build works fine in previous version (1.45.2).

**Comment by chinoto** [comment]
I'm new to this project and trying to figure out how to fix it up so it will compile. The solution I might go for is passing a closure instead of a block to the macro, which the macro could then call with `&mut self`.
Unfortunately I can't manage to grok this because in the final call to `fixturator!` on line 408 of `./crates/fixt/src/lib.rs`, `$munch` never seems to be used. I'm guessing that the `item!` macro somehow uses $munch, despite it not being passed in, similar to how self is used in fixturator calls without it being explicitly passed in.
Where can I find the definition of `item!`? Is it defined in a dependency outside this repository?

**Comment by chinoto** [comment]
It seems I loosened the dam and got flooded with even more errors, but at least they're contained to only three files. I'm done for tonight, this is what I've got so far: https://github.com/chinoto/holochain/commit/091928d9c5cc265e7e6c04ad7681b7b08664b8df

**Comment by chinoto** [comment]
I've managed to fix all the self errors and then there were some import errors as well. I'm not sure what to do about the last two errors since I don't have any background knowledge of this project.
https://github.com/holochain/holochain/compare/develop...chinoto:dc462aae
```rust
error[E0599]: no method named `next` found for struct `ElementFixturator<NewEntryHeader>` in the current scope
   --> crates/types/src/fixt.rs:338:77
    |
300 | / fixturator!(
301 | |     Element;
302 | |     vanilla fn element_with_no_entry(Signature, Header);
303 | |     curve NewEntryHeader self:this self:this {
...   |
320 | |     };
321 | | );
    | |__- method `next` not found for this
...
338 |               let element: Element = ElementFixturator::new_indexed(c, index).next().unwrap();
    |                                                                               ^^^^ method not found in `ElementFixturator<NewEntryHeader>`

error[E0599]: no method named `next` found for struct `ElementFixturator<NewEntryHeader>` in the current scope
   --> crates/types/src/fixt.rs:345:77
    |
300 | / fixturator!(
301 | |     Element;
302 | |     vanilla fn element_with_no_entry(Signature, Header);
303 | |     curve NewEntryHeader self:this self:this {
...   |
320 | |     };
321 | | );
    | |__- method `next` not found for this
...
345 |               let element: Element = ElementFixturator::new_indexed(u, index).next().unwrap();
    |                                                                               ^^^^ method not found in `ElementFixturator<NewEntryHeader>`
```
